### ISSUE TITLE
Link to download does not work

### ISSUE THREAD

**Issue by rabol** [MicrosoftDocs/DynamicsAX2012-technet#106]
[Enter feedback here]
'Go to the Services Download page.'

The link to download tihs addon does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da97ce64-93d7-2070-e7a7-4b8a3cfd1519
* Version Independent ID: 3361ba48-e4f4-945f-1c65-e2d3aff8fe7a
* Content: [Dynamics AX Intelligent Data Management Framework (IDMF)](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/microsoft-dynamics-ax-intelligent-data-management-framework-idmf)
* Content Source: [dynamicsax2012-technet/microsoft-dynamics-ax-intelligent-data-management-framework-idmf.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/microsoft-dynamics-ax-intelligent-data-management-framework-idmf.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by pennij** [comment]
Hi! Thanks for the feedback! The link takes you to the Lifecycle Services login page. You need to login in to the app to access the download page.
