### ISSUE TITLE
Path to Work item queues

### ISSUE THREAD

**Issue by Khalil-Dev** [MicrosoftDocs/DynamicsAX2012-technet#114]
Please notice that the right path to reach Work item queues, it's :
Organization administration &gt;Workflow &gt; Work item queues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 103f2acc-f5b0-d015-bd26-d1e136a644dc
* Version Independent ID: 9096664f-4020-0022-b3c8-a004e4094dfe
* Content: [Create a work item queue](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/create-a-work-item-queue#feedback)
* Content Source: [dynamicsax2012-technet/create-a-work-item-queue.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/create-a-work-item-queue.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by tonyafehr** [comment]
This topic has been updated. Thanks!
