### ISSUE TITLE
Client performance options page for Finance and Operations

### ISSUE THREAD

**Issue by pturegano** [MicrosoftDocs/DynamicsAX2012-technet#127]
This page is very useful. Needs to be created for Finance and Operations also as there are many new parameters on the "Client performance options" form which are difficult to understand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dd3b4e2-e42b-2350-a09e-ae104e3bf90f
* Version Independent ID: bb896ba6-9c0a-d722-4940-cb649e62a2be
* Content: [Configure client performance options](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/configure-client-performance-options#feedback)
* Content Source: [dynamicsax2012-technet/configure-client-performance-options.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/configure-client-performance-options.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by tonyafehr** [comment]
@pturegano, thanks for the great feedback. 
@jasongre, please review and consider making updates as needed.
