### ISSUE TITLE
Examples required

### ISSUE THREAD

**Issue by dahirongm** [MicrosoftDocs/DynamicsAX2012-technet#204]
It will be nice if some code examples are provided.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec78bf52-104d-4e5f-5b52-f95446433b13
* Version Independent ID: 677a595d-a392-6d5c-354a-4bb88ed375ef
* Content: [NonBindableActionController.GetCustomerGroups Method  (Microsoft.Dynamics.Retail.RetailServerLibrary.ODataControllers)](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/nonbindableactioncontroller-getcustomergroups-method-microsoft-dynamics-retail-retailserverlibrary-odatacontrollers#feedback)
* Content Source: [dynamicsax2012-technet/nonbindableactioncontroller-getcustomergroups-method-microsoft-dynamics-retail-retailserverlibrary-odatacontrollers.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/nonbindableactioncontroller-getcustomergroups-method-microsoft-dynamics-retail-retailserverlibrary-odatacontrollers.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by tonyafehr** [comment]
@RobinARH, please review

**Comment by RobinARH** [comment]
This content is archived.
