### ISSUE TITLE
XSLT is not valid

### ISSUE THREAD

**Issue by rabol** [MicrosoftDocs/DynamicsAX2012-technet#207]
Hi

We are having problems getting the above working.
After many tries we used a external tool to apply the XSLT to the XML created by AX and we get an error saying that the XSLT is not valid

can you provide an AIF messages and the final XML generated using the setup above?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fb2317c-d1ef-fe12-8a2e-3f2183b7c587
* Version Independent ID: 4d687d28-145d-384b-cd46-b4858023d7d3
* Content: [Set up positive pay](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/set-up-positive-pay)
* Content Source: [dynamicsax2012-technet/set-up-positive-pay.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/set-up-positive-pay.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by roschlom** [comment]
Thanks for contacting us although I'm sorry you're encountering issues getting the positive pay feature set up. This appears to be more of a support issue than a documentation issue. The topic at this URL, https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/lifecycle-services/lcs-support, lists a number of options for getting help, including opening a support request and a link for reaching out to the Dynamics community for help. The title of that topic is Get support for Finance and Operations apps or Lifecycle Services (LCS). Thanks again for using our documentation and reaching out to us.
