### ISSUE TITLE
The link for Management Reporter Installation Guide(PDF) is return 404

### ISSUE THREAD

**Issue by DanielBwln** [MicrosoftDocs/DynamicsAX2012-technet#218]
In section "After you install Management Reporter", there's a link "Management Reporter Installation Guide(PDF)", url is https://go.microsoft.com/fwlink/?linkid=325393, it's return 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45374797-e6dc-e6f1-20be-a111104fa1cc
* Version Independent ID: 0e4a4425-7c8d-aacd-dda9-120e3c19e3e7
* Content: [Install Management Reporter server components](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/install-management-reporter-server-components#feedback)
* Content Source: [dynamicsax2012-technet/install-management-reporter-server-components.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/install-management-reporter-server-components.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by tonyafehr** [comment]
The link has been fixed. Thanks!
