### ISSUE TITLE
Powershell command modifies MorphX objects directly in the AOT - Confirm layer

### ISSUE THREAD

**Issue by AlexHimself** [MicrosoftDocs/DynamicsAX2012-technet#220]
The PowerShell command `Set-AXReportDataSource` modifies the MorphX object in the AOT under `\SSRS Reports\Report Datasources\DynamicsAXOLAP` (or whatever your `DataSourceName` parameter is).

Confirm by examining the AOT and verify the change is in the correct layer. The `-ServicesFilePath` switch on the PowerShell command does not seem to work correctly to get in the desired layer in all instances of AX.

If change is in the wrong layer, export the MorphX object via XPO, delete it from incorrect layer, then connect to correct layer and import XPO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e72559d7-00b7-3f0b-1359-50a079bc680a
* Version Independent ID: b49da538-5336-6f40-14b6-3a4f516ce3e1
* Content: [Update the OLAP data source](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/update-the-olap-data-source)
* Content Source: [dynamicsax2012-technet/update-the-olap-data-source.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/update-the-olap-data-source.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by RobinARH** [comment]
Thanks for the feedback. We don't plan to update the topic.

**Comment by AlexHimself** [comment]
At https://docs.microsoft.com/en-us/dynamicsax-2012/set-axreportdatasource it is documented that `-ServicesFilePath` allows you to use a client configuration (.AXC).

You don't want to let users know this **does not work**?
