### ISSUE TITLE
need I define a data contract class if I don't have any parameter to pass?

### ISSUE THREAD

**Issue by smartczh** [MicrosoftDocs/DynamicsAX2012-technet#221]
ATT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 161a44aa-07d6-3f59-ce2a-9d3be9923686
* Version Independent ID: 6f188180-ac05-5c66-1116-e5070cf3d7a1
* Content: [How to: Use a Report Data Provider Class in a Report](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/how-to-use-a-report-data-provider-class-in-a-report#feedback)
* Content Source: [dynamicsax2012-technet/how-to-use-a-report-data-provider-class-in-a-report.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/how-to-use-a-report-data-provider-class-in-a-report.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by tonyafehr** [comment]
@Khairunj, please review.
