### ISSUE TITLE
The article does not cover invoicing

### ISSUE THREAD

**Issue by SST1982** [MicrosoftDocs/DynamicsAX2012-technet#222]
Although the name of the article refers to invoicing, this part of processing an IC sales+purchase order is not covered in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4928f106-2c3f-c79c-ab1a-e374416bc402
* Version Independent ID: 09021171-18aa-e1b7-3713-37eeadedef38
* Content: [Create and invoice an intercompany sales order for internal use](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/create-and-invoice-an-intercompany-sales-order-for-internal-use)
* Content Source: [dynamicsax2012-technet/create-and-invoice-an-intercompany-sales-order-for-internal-use.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/create-and-invoice-an-intercompany-sales-order-for-internal-use.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by tonyafehr** [comment]
@SST1982, thanks for the feedback. 
@Khairunj, please review and consider making updates.
