### ISSUE TITLE
Out of Date or incorrect Search Priority for Cost and Transfer Price Hierarchies

### ISSUE THREAD

**Issue by DFThinkmax** [MicrosoftDocs/DynamicsAX2012-technet#223]
Hi,
We have found through testing that the search priority of cost/sales/transfer pricing listed above is not accurate for Dynamics 365 Project Management and Accounting (tested up to version 10.0.10)

I understand that this documentation has not been updated since 2014, and is specified for ax-2012, but no other documentation for sales/cost/transfer price search priorities for D365 FO Project management and accounting are available online (if any exists, i would appreciate a link). 

In our testing we have found that, the following tables are what is currently in D365 (10.0.10)

Transfer Price:

![image](https://user-images.githubusercontent.com/65350764/81946516-70b58500-95cd-11ea-833c-f5bcecfc7afb.png)

Cost/Sales Price:
![image](https://user-images.githubusercontent.com/65350764/81946539-7b701a00-95cd-11ea-9477-b289bcabf500.png)

To summarize, in our testing, we have found that the order of search Priority is determined as 1. Project 2. Resource 3. Role 4. Category, except in a few scenarios (transfer price entries 1 & 2 on tables above), which we believe to be bugs. We are looking for updated documentation to determine what is designed.                                   

*Note that at time of testing, entries containing both category + role are not possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2da0a582-0c4b-0ac2-0028-2fbd2f30279d
* Version Independent ID: d16b55e3-921d-6c9e-9d72-8444ce1bac64
* Content: [About cost prices, sales prices, and transfer prices in projects](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/about-cost-prices-sales-prices-and-transfer-prices-in-projects#feedback)
* Content Source: [dynamicsax2012-technet/about-cost-prices-sales-prices-and-transfer-prices-in-projects.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/about-cost-prices-sales-prices-and-transfer-prices-in-projects.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by DFThinkmax** [comment]
Seems that the makeshift tables made in the comment were unformatted :(

To summarize, in our testing, we have found that the order of search Priority is determined as 1. Project 2. Resource 3. Role 4. Category, except in a few scenarios, which we believe to be bugs. We are looking for updated documentation to determine what is designed.

**Comment by RobinARH** [comment]
This content is archived.
