### ISSUE TITLE
Customer Write-Off Reason Codes

### ISSUE THREAD

**Issue by crobertso** [MicrosoftDocs/DynamicsAX2012-technet#224]
The instruction under the heading of "Set up a reason code for write-off transactions" in this article seems only partially correct, getting users through the first table of necessary setup. Customer Reason Codes (Form Name: Reasons) are available from a path close to what is mentioned above, Accounts Receivable &gt; Setup &gt; Customer Reason Codes, but further setup is required on the Customer Write-Off Reason Codes table, accessible from Accounts Receivable &gt; Setup &gt; Customer Write-Off Reason Codes (Form Name: CustWriteOffFinancialReasonsSetup), which links to the Customer Reason Codes, Main Accounts, and Legal Entities. The Default Write-Off Reason Code selected in the Accounts Receivable Parameters pulls from the Customer Write-Off Reason Code table. Clarification of the process and necessary setups here would be helpful to those seeking guidance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fca5569-ad0e-a1a9-ea78-3688319f6799
* Version Independent ID: 357b19f0-87b9-1f32-8b92-cd29255138f2
* Content: [Set up collections](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/set-up-collections#feedback)
* Content Source: [dynamicsax2012-technet/set-up-collections.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/set-up-collections.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by RobinARH** [comment]
This content is archived.
