### ISSUE TITLE
Missing text at section (Intelligent Data Management Framework)

### ISSUE THREAD

**Issue by ilovebmw** [MicrosoftDocs/DynamicsAX2012-technet#231]
missing text at section **Intelligent Data Management Framework** after **Recommended uses:**

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bef0840-ea60-f6de-6f9f-0a2d38f1739d
* Version Independent ID: 549e96ce-287b-929c-efcf-8288fe474094
* Content: [Plan data import, export, and migration](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/plan-data-import-export-and-migration)
* Content Source: [dynamicsax2012-technet/plan-data-import-export-and-migration.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/plan-data-import-export-and-migration.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by sericks007** [comment]
@ilovebmw, thanks for making us aware of this issue.  I've contacted a PM about providing text here.

**Comment by RobinARH** [comment]
This content is archived.
