### ISSUE TITLE
D365FO Feature management refers to this AX2012 page

### ISSUE THREAD

**Issue by pvruyske** [MicrosoftDocs/DynamicsAX2012-technet#232]
The 'Learn more' hyperlink that is available in the Feature management workspace of D365FO for the feature 'Improvements to the Approve and Transfer jobs dialogs' refers to this AX2012 Docs page, which is of course not correct.
Where exactly can one find more information about 'Improvements to the Approve and Transfer jobs dialogs'?

![image](https://user-images.githubusercontent.com/50585884/86463725-55920680-bd2e-11ea-8453-6d5eb5e973e1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51458114-0e8f-b16c-d795-1ec152f539e1
* Version Independent ID: 728add4e-2b82-600d-559a-464cca595f0f
* Content: [About calculating, approving and transferring registrations](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/about-calculating-approving-and-transferring-registrations)
* Content Source: [dynamicsax2012-technet/about-calculating-approving-and-transferring-registrations.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/about-calculating-approving-and-transferring-registrations.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by RobinARH** [comment]
This content is archived.
