### ISSUE TITLE
PMA - Incorrect Project stage description

### ISSUE THREAD

**Issue by Kaypeegee** [MicrosoftDocs/DynamicsAX2012-technet#233]
[
![PMA - Project stage incorrect description](https://user-images.githubusercontent.com/21172204/87118953-428fb100-c2af-11ea-8a83-143d97f145db.png)
](url)
[Incorrect Project stage description,same description as Project statements. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 218aa34f-f80b-035e-6e62-cbe212b58914
* Version Independent ID: 1bdda3ad-ab33-f100-8b06-4758a8f7627d
* Content: [About Project management and accounting parameters](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/about-project-management-and-accounting-parameters)
* Content Source: [dynamicsax2012-technet/about-project-management-and-accounting-parameters.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/about-project-management-and-accounting-parameters.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by RobinARH** [comment]
This content is archived.
