### ISSUE TITLE
fixed asset status types

### ISSUE THREAD

**Issue by ashwin666** [MicrosoftDocs/DynamicsAX2012-technet#234]
I have detailed the fixed asset status types you can use it: 

https://ashdynamicsax.files.wordpress.com/2020/07/post41_img1-2.jpg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba43ac9-d4c7-85f9-3e52-e7bf00c69e74
* Version Independent ID: 31ccf20c-508a-c3ab-4418-27e2b403d436
* Content: [Set up value models](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/set-up-value-models)
* Content Source: [dynamicsax2012-technet/set-up-value-models.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/set-up-value-models.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by tonyafehr** [comment]
@ashwin666, thanks for the supplementary information.
