### ISSUE TITLE
Broken download link

### ISSUE THREAD

**Issue by AlexHimself** [MicrosoftDocs/DynamicsAX2012-technet#235]
The download link for the Print Management Integration Guide is dead.

Alternative source: https://www.axug.com/HigherLogic/System/DownloadDocumentFile.ashx?DocumentFileKey=44573e38-d8cf-4e5b-a1fe-d24890d4be8f

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92584914-e81f-a48c-c5cf-0943086daba7
* Version Independent ID: 70ad08ab-021c-c7da-48ec-f0591805f6e6
* Content: [Print Management Integration Guide](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/print-management-integration-guide)
* Content Source: [dynamicsax2012-technet/print-management-integration-guide.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/print-management-integration-guide.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by tonyafehr** [comment]
The link should work now.

**Comment by AlexHimself** [comment]
> The link should work now.

Still broken
