### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by AlexHimself** [MicrosoftDocs/DynamicsAX2012-technet#237]
The URL appears broken for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fc5139e-9661-a3f1-845f-aeac8b8699f8
* Version Independent ID: 029a8d1b-f380-8da3-8f07-f46c62594306
* Content: [Testing best practices (White paper)](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/testing-best-practices-white-paper)
* Content Source: [dynamicsax2012-technet/testing-best-practices-white-paper.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/testing-best-practices-white-paper.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by tonyafehr** [comment]
The link should work now.
