### ISSUE TITLE
"Navigation Path Not Found"

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/DynamicsAX2012-technet#239]
Under "Create cycle counting work manually", step 1 shows:

Navigation Path Not Found

–or–

Navigation Path Not Found

The article appears to have been left incomplete in this area.  Please update the article with the navigation path(es).

Screen capture:

![image](https://user-images.githubusercontent.com/30128768/89910541-5e43eb00-dbbe-11ea-8b00-b21fb71a190e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d95f4685-bc01-1be2-2919-1b5f92910b03
* Version Independent ID: 745d447c-6d3c-051c-83bb-70988060ecbd
* Content: [Perform cycle counting in a warehouse location](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/perform-cycle-counting-in-a-warehouse-location)
* Content Source: [dynamicsax2012-technet/perform-cycle-counting-in-a-warehouse-location.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/perform-cycle-counting-in-a-warehouse-location.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by RobinARH** [comment]
This content is archived.
