### ISSUE TITLE
Incorrect spelling in example

### ISSUE THREAD

**Issue by v-anluon** [MicrosoftDocs/DynamicsAX2012-technet#240]
Incorrect spelling in Example in step 4 for Running powershell scripts to configure Async Client.  Correct filename should be sc-settings.xml (currently sc-settings.xm)
![image](https://user-images.githubusercontent.com/58959553/90751582-86d78d80-e300-11ea-9e1e-aa77b146ff95.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f80ddd-2684-7208-407c-ada6d8be4899
* Version Independent ID: c27f2a5a-4649-1848-5180-ba6cd694af80
* Content: [Install Commerce Data Exchange: Async Client](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/install-commerce-data-exchange-async-client)
* Content Source: [dynamicsax2012-technet/install-commerce-data-exchange-async-client.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/install-commerce-data-exchange-async-client.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by tonyafehr** [comment]
@v-anluon, thanks for the feedback. I fixed this issue.
