### ISSUE TITLE
Need clarification on Print the picking lists

### ISSUE THREAD

**Issue by Bijan-Ghofranian** [MicrosoftDocs/DynamicsAX2012-technet#253]
The documentation for Printing the "Picking lists" states the following and I copied it verbatim:

To print the picking list, follow these steps:

1. **Navigation Path Not Found**

2. Expand the Batches FastTab.
.....
Step 1 does not make any sense! 
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28fec681-b49b-a287-925c-9722ec74769e
* Version Independent ID: 77191e84-5887-4b2a-d284-f696d9a1e720
* Content: [Release items to warehouse by using the picking workbench](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/release-items-to-warehouse-by-using-the-picking-workbench)
* Content Source: [dynamicsax2012-technet/release-items-to-warehouse-by-using-the-picking-workbench.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/release-items-to-warehouse-by-using-the-picking-workbench.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by RobinARH** [comment]
This content is archived.
