### ISSUE TITLE
Wrong links to articles

### ISSUE THREAD

**Issue by Y4nek** [MicrosoftDocs/DynamicsAX2012-technet#257]
5 out of 6 links are wrong.
First is ok.
General management cmdlets
https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/general-management-cmdlets

Flexible authentication cmdlets
https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/enterprise-portal-and-sharepoint-flexible-authentication-cmdlets

Model and model store cmdlets
https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/model-and-model-store-cmdlets

Report server management cmdlets
https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/report-server-management-cmdlets

User and role-based security cmdlets
https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/user-and-role-based-security-cmdlets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34474385-4e83-a0b3-bdd9-0715e8405a1c
* Version Independent ID: 649f82fe-e764-3357-df04-c0f8ec206b50
* Content: [Windows PowerShell for Microsoft Dynamics AX](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/windows-powershell-for-microsoft-dynamics-ax)
* Content Source: [dynamicsax2012-technet/windows-powershell-for-microsoft-dynamics-ax.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/windows-powershell-for-microsoft-dynamics-ax.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by RobinARH** [comment]
This content is archived.
