### ISSUE TITLE
Typo - Reverse but should be Reserve

### ISSUE THREAD

**Issue by SamRonchetti** [MicrosoftDocs/DynamicsAX2012-technet#258]
[Hiya, 

There is a typo in the document. Spelling of reserve is spelt reverse.

Thanks
Sam]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 942d7937-a2f6-e821-820c-c8b08254df5a
* Version Independent ID: 5d481fb5-9246-2104-6313-0bd8a13a5b57
* Content: [Reserve inventory automatically for a sales order](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/reserve-inventory-automatically-for-a-sales-order)
* Content Source: [dynamicsax2012-technet/reserve-inventory-automatically-for-a-sales-order.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/reserve-inventory-automatically-for-a-sales-order.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by tonyafehr** [comment]
Fixed.
