### ISSUE TITLE
Error: .NET authentication component

### ISSUE THREAD

**Issue by nishankjain8** [MicrosoftDocs/DynamicsAX2012-technet#260]
Unable to compile code in .NET authentication components.
Error in line below
principal = AuthenticationHelper.Authenticate(listenUri, message.Headers, message.Properties);

Added System.Security.Authentication in project reference.

Visual studio version: 2013
Framework version: 4.6.1
Error: The name 'AuthenticationHelper' does not exist in the current context

**Comment by tonyafehr** [comment]
Unfortunately, we're unable to handle Support requests for the product here. To contact Support, consider one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
