### ISSUE TITLE
Defines the effective period in months or years

### ISSUE THREAD

**Issue by MattGuoM** [MicrosoftDocs/DynamicsAX2012-technet#261]
[Enter feedback here]
The Doc says: The shelf life defines the effective period of a product as measured in days, months, or years.
My question is how to defines the effective period in months or years? I couldn't find any where to access it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e2303ed-fc7f-b601-bd1a-9c43a6949cec
* Version Independent ID: 0185aef3-42c0-84ff-cb7c-449890e3e8cf
* Content: [Reset shelf life dates for an inventory batch](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/reset-shelf-life-dates-for-an-inventory-batch)
* Content Source: [dynamicsax2012-technet/reset-shelf-life-dates-for-an-inventory-batch.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/reset-shelf-life-dates-for-an-inventory-batch.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by RobinARH** [comment]
This content is archived.
