### ISSUE TITLE
Applies To: Microsoft Dynamics AX 2012 R3

### ISSUE THREAD

**Issue by DrGee-gethub** [MicrosoftDocs/DynamicsAX2012-technet#262]
the header states "Applies To: Microsoft Dynamics AX 2012 R3"
in the body in a NOTE is then states "This walkthrough is **_not_** intended for users of the versions of the Data Import/Export Framework that ship with cumulative update 7 for Microsoft Dynamics AX 2012 R2 or Microsoft Dynamics **AX 2012 R3**."

Can you clarify or restate the applicability?
So is this page for AX 2012 R3 or Not?

thanks
-drg
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 769b99e2-c584-d09d-635d-8c2475055a25
* Version Independent ID: b95b12a5-7604-bffd-1d17-8f09a8850d3f
* Content: [Copy data between Dynamics AX companies](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/walkthrough-copy-data-between-microsoft-dynamics-ax-companies-dixf-dmf)
* Content Source: [dynamicsax2012-technet/walkthrough-copy-data-between-microsoft-dynamics-ax-companies-dixf-dmf.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/walkthrough-copy-data-between-microsoft-dynamics-ax-companies-dixf-dmf.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by RobinARH** [comment]
This content is archived.
