### ISSUE TITLE
"https://go.microsoft.com/fwlink/?linkid=213212" on the page is broken

### ISSUE THREAD

**Issue by nenea-nelu** [MicrosoftDocs/DynamicsAX2012-technet#265]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4d68ed5-e5be-e34e-9a8b-b0fb7811ae16
* Version Independent ID: 428f235d-37a9-1889-4749-2505cc3aa68b
* Content: [Configure SQL Server and storage settings](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/configure-sql-server-and-storage-settings#feedback)
* Content Source: [dynamicsax2012-technet/configure-sql-server-and-storage-settings.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/configure-sql-server-and-storage-settings.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by tonyafehr** [comment]
@nenea-nelu, this link has been fixed. Thanks for the feedback.
