### ISSUE TITLE
Broken URL for Oracle to Microsoft SQL Server Data Migration Assistant for Microsoft Dynamics AX Installation Guide

### ISSUE THREAD

**Issue by Chrisslima** [MicrosoftDocs/DynamicsAX2012-technet#266]
The link of Customer Source is broken: Oracle to Microsoft SQL Server Data Migration Assistant for Microsoft Dynamics AX Installation Guide. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9db0f2dc-647a-785c-fd16-004e1918ef5f
* Version Independent ID: 171c49a0-897c-1411-db6f-6c0207fe3d75
* Content: [Supported upgrade paths](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/supported-upgrade-paths#upgrading-from-a-microsoft-dynamics-ax-source-system-that-uses-an-oracle-database)
* Content Source: [dynamicsax2012-technet/supported-upgrade-paths.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/supported-upgrade-paths.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by tonyafehr** [comment]
Closing this, as upgrading to AX2012 is no longer supported.
