### ISSUE TITLE
Link is dead on page

### ISSUE THREAD

**Issue by ryanpalus** [MicrosoftDocs/DynamicsAX2012-technet#269]
The link to the financial dimension whitepaper is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cd46bd8-b305-8e61-c0cb-4373de8c96f0
* Version Independent ID: b2101cbc-7f68-bddc-6c38-6786b7c0f582
* Content: [Implementing the Account and Financial Dimensions Framework (White paper)](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/implementing-the-account-and-financial-dimensions-framework-white-paper)
* Content Source: [dynamicsax2012-technet/implementing-the-account-and-financial-dimensions-framework-white-paper.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/implementing-the-account-and-financial-dimensions-framework-white-paper.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by tonyafehr** [comment]
The link opens the white paper that is found at this address: [https://go.microsoft.com/fwlink/?linkid=213133](https://go.microsoft.com/fwlink/?linkid=213133). The link opens a file, which you can download and does not open a new window. Most likely the file download is located at the bottom of your browser.
