### ISSUE TITLE
No Outputs of type ModelManifest fpr Install-AXModel cmdlet

### ISSUE THREAD

**Issue by banoz** [MicrosoftDocs/DynamicsAX2012-technet#270]
Output is always a text, no way to get a manifest object.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e87bf68b-72a5-445a-b837-3d9c4acc3704
* Version Independent ID: 63625afe-1cd8-1511-0a36-243d5986d0be
* Content: [Install-AXModel](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/install-axmodel)
* Content Source: [dynamicsax2012-technet/install-axmodel.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/install-axmodel.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by tonyafehr** [comment]
@banoz, we've ended mainstream support for AX2012, so we will not be updating this topic to accommodate your request.
