### ISSUE TITLE
Multiple dead links on this docs page

### ISSUE THREAD

**Issue by AlexHimself** [MicrosoftDocs/DynamicsAX2012-technet#271]
There are multiple dead links that redirect to a generic Microsoft landing page on this docs site.

How To: Create or Modify a Service Bus Service Namespace. (https://go.microsoft.com/fwlink/?linkid=313633)

Developing Secure Mobile Apps for Microsoft Dynamics AX 2012. (https://go.microsoft.com/fwlink/?linkid=393709%26clcid=0x409)

Deploying Federation Servers (https://go.microsoft.com/fwlink/?linkid=393711%26clcid=0x409)
Configure a New Federation Server (https://go.microsoft.com/fwlink/?linkid=393712%26clcid=0x409)

I didn't click on every link but there are probably more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3aac6ae-8429-3614-46cc-5602eb667db8
* Version Independent ID: bef5a414-0e27-efb7-8793-92475cd626f3
* Content: [Deploy Microsoft Dynamics AX Services to the Windows Azure Service Bus](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/deploy-microsoft-dynamics-ax-services-to-the-windows-azure-service-bus)
* Content Source: [dynamicsax2012-technet/deploy-microsoft-dynamics-ax-services-to-the-windows-azure-service-bus.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/deploy-microsoft-dynamics-ax-services-to-the-windows-azure-service-bus.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by tonyafehr** [comment]
@AlexHimself, the links should be fixed now.
