### ISSUE TITLE
Practical examples are not given in the document for using Sub-workflow

### ISSUE THREAD

**Issue by Neeraj2912** [MicrosoftDocs/DynamicsAX2012-technet#275]
Sub-workflow process is defined in the document but without linking to any practical example or scenario. Practical examples/ scenarios can be very useful in understanding this wonderful functionality.
Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 681d9ff9-028d-c8b9-c6e9-4b19df702331
* Version Independent ID: 14dc5067-50e5-c921-9624-fc1c73aa04ba
* Content: [Configure a subworkflow](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/configure-a-subworkflow)
* Content Source: [dynamicsax2012-technet/configure-a-subworkflow.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/configure-a-subworkflow.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by sericks007** [comment]
You might want to use the [Communities site](https://community.dynamics.com/) to see if someone can assist with this.
