### ISSUE TITLE
Payment schedule

### ISSUE THREAD

**Issue by angeloi9** [MicrosoftDocs/DynamicsAX2012-technet#276]
What is the function for the 2 fields minimun in this form?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de62a192-8a38-b00f-bb5d-c7baa885a220
* Version Independent ID: a66ef11f-a1b2-8726-5d56-060d02ff35c7
* Content: [Set up payment schedules on orders](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/set-up-payment-schedules-on-orders)
* Content Source: [dynamicsax2012-technet/set-up-payment-schedules-on-orders.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/set-up-payment-schedules-on-orders.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by RobinARH** [comment]
This content is archived.
