### ISSUE TITLE
Incorrect instructions for setting up worker as resource

### ISSUE THREAD

**Issue by Kelkane** [MicrosoftDocs/DynamicsAX2012-technet#277]
[Enter feedback here]
Within this documentation, it states that if you want to enter a Resource of type Human resource, that you can select the worker from the "Send list of products" field on the General tab. It states this twice on this docs page. 

![image](https://user-images.githubusercontent.com/63654741/108215400-4c0fb000-70ff-11eb-99f9-8ffae9fcdfe5.png)

When you look in the system, it is the Worker field. 

![image](https://user-images.githubusercontent.com/63654741/108215441-59c53580-70ff-11eb-8d3b-bccd5a7748a3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b9a5448-2649-319a-6eff-5fef5ec99aaf
* Version Independent ID: ffdc0b07-db3f-2a09-86b9-9fccd780d02a
* Content: [Create and maintain operations resources](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/create-and-maintain-operations-resources)
* Content Source: [dynamicsax2012-technet/create-and-maintain-operations-resources.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/create-and-maintain-operations-resources.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by andreabichsel** [comment]
Thanks for catching this! I fixed it, and changes should be live soon.
