### ISSUE TITLE
Unable to find savecart function 

### ISSUE THREAD

**Issue by javafun** [MicrosoftDocs/DynamicsAX2012-technet#29]
Is the code snippet only applicable for certain version? I am on the cu9, the order manager doesn’t have savecart method.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4dbe88c-209b-a58e-1105-d81bacac2500
* Version Independent ID: fc3d9927-8b37-270c-d61b-21c09e24f1bf
* Content: [Walkthrough: Adding Properties to a Sales Order](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/walkthrough-adding-properties-to-a-sales-order)
* Content Source: [dynamicsax2012-technet/walkthrough-adding-properties-to-a-sales-order.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/walkthrough-adding-properties-to-a-sales-order.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by pennij** [comment]
Hi! Version information has been added to the top of the topic. Thanks for your feedback!
