### ISSUE TITLE
Receive AttributeTextValue serialization with above steps

### ISSUE THREAD

**Issue by javafun** [MicrosoftDocs/DynamicsAX2012-technet#31]
Hi

I received the following error with the above-mentioned steps, can you provide some advice? 

Type 'Microsoft.Dynamics.Commerce.Runtime.DataModel.AttributeTextValue' with data contract name 'AttributeTextValue:http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Commerce.Runtime.DataModel' is not expected. Consider using a DataContractResolver if you are using DataContractSerializer or add any types not known statically to the list of known types - for example, by using the KnownType Attribute attribute or by adding them to the list of known types passed to the serializer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4dbe88c-209b-a58e-1105-d81bacac2500
* Version Independent ID: fc3d9927-8b37-270c-d61b-21c09e24f1bf
* Content: [Walkthrough: Adding Properties to a Sales Order](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/walkthrough-adding-properties-to-a-sales-order)
* Content Source: [dynamicsax2012-technet/walkthrough-adding-properties-to-a-sales-order.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/walkthrough-adding-properties-to-a-sales-order.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by pennij** [comment]
Thanks for contacting us. If you need assistance, contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
