### ISSUE TITLE
The link doesn't work

### ISSUE THREAD

**Issue by norelc** [MicrosoftDocs/DynamicsAX2012-technet#32]
I don't see any IDMF information when I click on the link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3386efda-e10d-c725-8c76-d00c32fbcea7
* Version Independent ID: 0430bef2-d446-6982-668a-4d1ad2a8278a
* Content: [Overview of the Microsoft Dynamics AX Intelligent Data Management Framework (IDMF)](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/overview-of-the-microsoft-dynamics-ax-intelligent-data-management-framework-idmf)
* Content Source: [dynamicsax2012-technet/overview-of-the-microsoft-dynamics-ax-intelligent-data-management-framework-idmf.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/overview-of-the-microsoft-dynamics-ax-intelligent-data-management-framework-idmf.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by pennij** [comment]
Hi! The link has been fixed. Thanks for the feedback!
