### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by nestodorova** [MicrosoftDocs/DynamicsAX2012-technet#34]
The link to the paper is not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 514c29ed-4fe0-d54b-8bec-2d825d936d0e
* Version Independent ID: 0f915de7-5c91-c86b-1996-6608828f7f89
* Content: [Demand forecasting in Microsoft Dynamics AX 2012 R3](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/demand-forecasting-in-microsoft-dynamics-ax-2012-r3)
* Content Source: [dynamicsax2012-technet/demand-forecasting-in-microsoft-dynamics-ax-2012-r3.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/demand-forecasting-in-microsoft-dynamics-ax-2012-r3.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by pennij** [comment]
Hi! The link has been fixed. Thanks for the feedback!
