### ISSUE TITLE
i have used scanner but still it identifies it as manually

### ISSUE THREAD

**Issue by Ihsan666** [MicrosoftDocs/DynamicsAX2012-technet#41]
i have displayed messageBox for each BarcodeEntryType and i have scanned a barcode in dynamics POS but it always displaying Manually entered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad5da804-92c1-a7c7-8bb8-b55e5ead8d28
* Version Independent ID: 599fb6b7-66bb-7b50-2393-431d68706ca6
* Content: [BarcodeEntryType Enumeration (Microsoft.Dynamics.Retail.Pos.Contracts.Services)](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/barcodeentrytype-enumeration-microsoft-dynamics-retail-pos-contracts-services)
* Content Source: [dynamicsax2012-technet/barcodeentrytype-enumeration-microsoft-dynamics-retail-pos-contracts-services.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/barcodeentrytype-enumeration-microsoft-dynamics-retail-pos-contracts-services.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by pennij** [comment]
Thanks for contacting us. If you need assistance, contact Support using one of the options described here: [Support contact options](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/lifecycle-services/lcs-support). In particular, you might want to go to the [Dynamics 365 community page](https://community.dynamics.com/) to get help with your questions from the Dynamics community.
