### ISSUE TITLE
Apply to Dynamics 365 Unified Operations?

### ISSUE THREAD

**Issue by JeffLoucksPersonal** [MicrosoftDocs/DynamicsAX2012-technet#61]
Hi, Could you update the article to discuss if it applies to D365 Unified Operations? Does it have a new name? Are these now called tasks and workflows?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00f2565b-b9a3-c29d-77b2-88c07e0b131c
* Version Independent ID: e79af4d3-7c8d-b1c6-44d9-7ba6aae20329
* Content: [Configure work item queues](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/configure-work-item-queues)
* Content Source: [dynamicsax2012-technet/configure-work-item-queues.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/configure-work-item-queues.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by pennij** [comment]
Hi! Version information was added to the top of the topic. Thanks for the feedback!
