### ISSUE TITLE
Article "More information" - invalid link

### ISSUE THREAD

**Issue by fandas-eu** [MicrosoftDocs/DynamicsAX2012-technet#66]
Link to the whitepaper "Implementing ..." is not valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d4ac161-2e49-f617-88a6-f2ba8e6cfda7
* Version Independent ID: 0e620f15-9fb5-11ce-6993-759e1163f3c7
* Content: [What's new: Financial dimensions framework](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/what-s-new-financial-dimensions-framework)
* Content Source: [dynamicsax2012-technet/what-s-new-financial-dimensions-framework.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/what-s-new-financial-dimensions-framework.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by pennij** [comment]
Hi! The link has been fixed. Thanks for the feedback!
