### ISSUE TITLE
Visio link broken

### ISSUE THREAD

**Issue by dodiggitydag** [MicrosoftDocs/DynamicsAX2012-technet#69]
The link to the Visio diagram is broken and I seem to have lost my copy of it.  Can you fix?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 066925e3-e276-f06a-2d94-a4d91127f05b
* Version Independent ID: 62461a81-748b-4475-896d-36ff150233b6
* Content: [Apply updates and hotfixes](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/apply-updates-and-hotfixes)
* Content Source: [dynamicsax2012-technet/apply-updates-and-hotfixes.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/apply-updates-and-hotfixes.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by pennij** [comment]
Hi! The link has been fixed. Thanks for the feedback!
