### ISSUE TITLE
Downloadable PDF and Visio files are not available

### ISSUE THREAD

**Issue by dodiggitydag** [MicrosoftDocs/DynamicsAX2012-technet#74]
I would like to include this diagram in some documentation I am creating however the downloadable PDF and Visio files for AX 2012 upgrades link is broken / 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 988ef94d-067e-5202-5477-2989fea8a517
* Version Independent ID: 2d462e70-fb2f-3c48-57b6-7d4a97bdb2d2
* Content: [Technical diagrams for upgrade scenarios](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/technical-diagrams-for-upgrade-scenarios)
* Content Source: [dynamicsax2012-technet/technical-diagrams-for-upgrade-scenarios.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/technical-diagrams-for-upgrade-scenarios.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by pennij** [comment]
Hi! The links have been fixed. Thanks for the feedback!
