### ISSUE TITLE
Link "Security roles and licensing white paper" doesnt work

### ISSUE THREAD

**Issue by surjeet1981** [MicrosoftDocs/DynamicsAX2012-technet#80]
Link "Security roles and licensing white paper" doesnt work on this page. It gives an error that the page is not valid

This site can’t be reached The webpage at http://download.microsoft.com/download/1/A/4/1A4CA2CF-FE7C-4629-921C-B41CD63FC021/Microsoft_Dynamics_AX_2012_R2_Licensing_Guide-Customer_EditionDec2012.pdf might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96b540a1-d103-2e12-ddfb-be1447bb8032
* Version Independent ID: acbc7f97-31d4-5013-174c-1a2fecaa9db2
* Content: [Security role reference](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/security-role-reference#feedback)
* Content Source: [dynamicsax2012-technet/security-role-reference.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/security-role-reference.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by pennij** [comment]
Thanks for letting us know about the broken link. The link has been fixed!
