### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Y4nek** [MicrosoftDocs/DynamicsAX2012-technet#81]
Link to the poster is also broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 066925e3-e276-f06a-2d94-a4d91127f05b
* Version Independent ID: 62461a81-748b-4475-896d-36ff150233b6
* Content: [Apply updates and hotfixes](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/apply-updates-and-hotfixes#feedback)
* Content Source: [dynamicsax2012-technet/apply-updates-and-hotfixes.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/apply-updates-and-hotfixes.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by pennij** [comment]
Thanks for letting us know about the broken link. The link has been fixed!
