### ISSUE TITLE
Link to "Install Integration Services" does not work

### ISSUE THREAD

**Issue by danielzook** [MicrosoftDocs/DynamicsAX2012-technet#84]
The link in the bullet point "A running instance of Microsoft SQL Server Integration Services" refers to "Install Integration Services", with the anchor http://go.microsoft.com/fwlink/?linkid=394975%26clcid=0x409

This doesn't work.  When following that link, one ends up on the MS home page.  The link should be this instead:
http://go.microsoft.com/fwlink/?linkid=394975

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24ec7537-6fe6-a758-aee7-ad8af246419b
* Version Independent ID: 6a7b0302-4f5f-9844-f9ed-a322603d7b6b
* Content: [Install the Data import/export framework (AX 2012 R3)](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/install-the-data-import-export-framework-ax-2012-r3#feedback)
* Content Source: [dynamicsax2012-technet/install-the-data-import-export-framework-ax-2012-r3.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/install-the-data-import-export-framework-ax-2012-r3.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by tonyafehr** [comment]
@danielzook, thanks for noting this. I've updated the link.
