### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by UnaFresa** [MicrosoftDocs/DynamicsAX2012-technet#98]
The link for "Overview of Microsoft Dynamics AX build numbers" doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9491f77f-c24f-3b14-5ead-1c25cd56621a
* Version Independent ID: a82ee2af-c913-3b4c-7f38-73d3d6b5d4d1
* Content: [Find out which version of Microsoft Dynamics AX you are using](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/find-out-which-version-of-microsoft-dynamics-ax-you-are-using#feedback)
* Content Source: [dynamicsax2012-technet/find-out-which-version-of-microsoft-dynamics-ax-you-are-using.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/find-out-which-version-of-microsoft-dynamics-ax-you-are-using.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by pennij** [comment]
Hi! Thanks for letting us know about the broken link. The link has been fixed!
